# Generated by Django 5.1.3 on 2024-11-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0003_customuser_remove_profile_address1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
