# Generated by Django 5.1.3 on 2024-11-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
