# Generated by Django 5.1.3 on 2024-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0006_rename_phone_number_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
