# Generated by Django 5.1.3 on 2024-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0009_profile_created_at_profile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_temp',
            field=models.BooleanField(default=True),
        ),
    ]
