# Generated by Django 5.1.3 on 2024-11-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0010_profile_is_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
