# Generated by Django 5.1.3 on 2024-11-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0011_remove_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
