# Generated by Django 5.1.3 on 2024-11-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0012_rename_first_name_profile_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
