# Generated by Django 5.1.3 on 2024-11-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0013_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_superuser',
            new_name='is_admin',
        ),
    ]
