# Generated by Django 5.1.3 on 2024-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0014_rename_is_superuser_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_temp',
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('temp', '元請'), ('full_time', '正社員'), ('admin', '管理')], max_length=50),
        ),
    ]
