# Generated by Django 5.1.3 on 2024-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0015_remove_profile_is_admin_remove_profile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('元請', '元請'), ('正社員', '正社員'), ('管理', '管理')], max_length=50),
        ),
    ]
