# Generated by Django 5.1.3 on 2024-11-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0016_alter_profile_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Genba')),
                ('client', models.CharField(max_length=255, verbose_name='Client')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('job_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job description')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, null=True, related_name='attendees', to='genba.profile')),
                ('head_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_person', to='genba.profile')),
            ],
        ),
    ]
