# Generated by Django 5.1.3 on 2024-11-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0017_genba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genba',
            old_name='remarks',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='genba',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='genba.profile'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='head_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_person', to='genba.profile'),
        ),
    ]
