# Generated by Django 5.1.3 on 2024-11-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0018_rename_remarks_genba_note_alter_genba_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genba',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
