# Generated by Django 5.1.3 on 2024-11-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0021_alter_notification_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genba',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.CreateModel(
            name='Daily_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=10)),
                ('highway_start', models.CharField(blank=True, max_length=100)),
                ('highway_end', models.CharField(blank=True, max_length=100)),
                ('hightway_payment', models.CharField(blank=True, choices=[('現金', '現金'), ('カード', 'カード'), ('電子マネー', '電子マネー')], max_length=50)),
                ('parking', models.CharField(blank=True, max_length=100)),
                ('hotel', models.BooleanField(default=False)),
                ('other_payment', models.CharField(blank=True, max_length=100)),
                ('other_payment_amount', models.CharField(blank=True, max_length=100)),
                ('daily_details', models.CharField(blank=True, max_length=500)),
                ('daily_note', models.CharField(blank=True, max_length=500)),
                ('kentaikyo', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('genba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genba', to='genba.genba')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='genba.profile')),
            ],
        ),
    ]
