# Generated by Django 5.1.3 on 2024-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0022_alter_genba_note_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
