# Generated by Django 5.1.3 on 2024-11-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0023_daily_report_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_report',
            old_name='hightway_payment',
            new_name='highway_payment',
        ),
    ]
