# Generated by Django 5.1.3 on 2024-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0024_rename_hightway_payment_daily_report_highway_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_report',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='genba',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
