# Generated by Django 5.1.3 on 2024-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0025_alter_daily_report_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='shift',
            field=models.CharField(choices=[('日勤', '日勤'), ('夜勤', '夜勤')], default='日勤', max_length=50),
        ),
    ]
