# Generated by Django 5.1.3 on 2024-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0026_daily_report_shift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_report',
            new_name='DailyReport',
        ),
    ]
