# Generated by Django 5.1.3 on 2024-11-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0027_rename_daily_report_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='genba',
            name='color',
            field=models.CharField(blank=True, choices=[('#ff6961', '#ff6961'), ('#ffb480', '#ffb480'), ('#f8f38d', '#f8f38d'), ('#42d6a4', '#42d6a4'), ('#08cad1', '#08cad1'), ('#59adf6', '#59adf6'), ('#9d94ff', '#9d94ff'), ('#c780e8', '#c780e8')], max_length=30),
        ),
    ]
