# Generated by Django 5.1.3 on 2024-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0028_genba_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('元請', '元請'), ('正社員', '正社員'), ('管理', '管理')], default='管理', max_length=50),
        ),
    ]
