# Generated by Django 5.1.3 on 2024-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0030_alter_genba_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genba',
            name='color',
            field=models.CharField(choices=[('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30),
        ),
    ]
