# Generated by Django 5.1.3 on 2024-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0031_alter_genba_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='end_time',
            field=models.TimeField(verbose_name='作業終了日'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(verbose_name='作業終了日'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='color',
            field=models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30),
        ),
    ]
