# Generated by Django 5.1.3 on 2024-12-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0032_alter_dailyreport_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
