# Generated by Django 5.1.3 on 2024-12-04 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0033_dailyreport_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genba',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
