# Generated by Django 5.1.3 on 2024-12-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0034_rename_created_at_genba_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
