# Generated by Django 5.1.3 on 2024-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0035_rename_created_at_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='hotel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
