# Generated by Django 5.1.3 on 2024-12-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0036_alter_dailyreport_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genba',
            name='is_active',
        ),
        migrations.AddField(
            model_name='genba',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('下請け', '下請け'), ('正社員', '正社員'), ('管理', '管理')], default='正社員', max_length=50),
        ),
    ]
