# Generated by Django 5.1.3 on 2024-12-11 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0037_remove_genba_is_active_genba_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='break_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='休憩時間'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='daily_details',
            field=models.CharField(blank=True, max_length=500, verbose_name='作業内容'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='daily_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='distance',
            field=models.CharField(max_length=10, verbose_name='距離'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='highway_end',
            field=models.CharField(blank=True, max_length=100, verbose_name='高速降り'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='highway_payment',
            field=models.CharField(blank=True, choices=[('現金', '現金'), ('カード', 'カード'), ('電子マネー', '電子マネー')], max_length=50, verbose_name='高速料金'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='highway_start',
            field=models.CharField(blank=True, max_length=100, verbose_name='高速乗り'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, verbose_name='宿泊'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='kentaikyo',
            field=models.BooleanField(default=False, verbose_name='建退共'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='other_payment',
            field=models.CharField(blank=True, max_length=100, verbose_name='その他支払い'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='other_payment_amount',
            field=models.CharField(blank=True, max_length=100, verbose_name='その他支払い金額'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='parking',
            field=models.CharField(blank=True, max_length=100, verbose_name='駐車'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='shift',
            field=models.CharField(choices=[('日勤', '日勤'), ('夜勤', '夜勤')], default='日勤', max_length=50, verbose_name='日勤夜勤'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(verbose_name='作業開始日'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='address',
            field=models.CharField(max_length=255, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='client',
            field=models.CharField(max_length=255, verbose_name='取引先'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='color',
            field=models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30, verbose_name='現場色'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='end_date',
            field=models.DateTimeField(verbose_name='作業終了日'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='job_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作業内容'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='name',
            field=models.CharField(max_length=255, verbose_name='現場'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='genba',
            name='start_date',
            field=models.DateTimeField(verbose_name='作業開始日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('下請け', '下請け'), ('正社員', '正社員'), ('管理', '管理')], default='正社員', max_length=50, verbose_name='雇用形態'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=20, verbose_name='お名前'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='現役中'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='携帯電話'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
