# Generated by Django 5.1.3 on 2024-12-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0038_dailyreport_break_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='break_time',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='休憩時間'),
        ),
    ]
