# Generated by Django 5.1.3 on 2024-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0039_alter_dailyreport_break_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='break_time',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='休憩時間'),
        ),
    ]
