# Generated by Django 5.1.3 on 2024-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0040_alter_dailyreport_break_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='break_time',
            new_name='break_time_numeric',
        ),
    ]
