# Generated by Django 5.1.3 on 2024-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0041_rename_break_time_dailyreport_break_time_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='break_time_numeric',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='休憩時間'),
        ),
    ]
