# Generated by Django 5.1.3 on 2024-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0043_remove_dailyreport_break_time_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='break_time_numeric',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='休憩時間'),
            preserve_default=False,
        ),
    ]
