# Generated by Django 5.1.3 on 2024-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0044_dailyreport_break_time_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='break_time_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='休憩時間'),
        ),
    ]
