# Generated by Django 5.1.3 on 2024-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0045_alter_dailyreport_break_time_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='break_time_numeric',
            field=models.CharField(blank=True, default=123, max_length=10, verbose_name='休憩時間'),
            preserve_default=False,
        ),
    ]
