# Generated by Django 5.1.3 on 2024-12-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0046_alter_dailyreport_break_time_numeric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='break_time_numeric',
        ),
    ]
